update readme with hsf cookiecutter readme template
hsf-training/hsf-training-cicd-basics-webpage pull request #15
Opened 2023-04-20 04:49 UTC by amanmdesai

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to respond to your contribution.
To ensure that the right people get notified, you can tag some of the last contributors with `@githubname`.

Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).

You may delete these instructions from your pull request.

\- HSF Training
</details>

2023-06-19 16:58 UTC, wdconinc commented
No rebase button... @amanmdesai can you rebase or merge gh-pages into this branch?

2023-06-20 03:18 UTC, amanmdesai commented
> No rebase button... @amanmdesai can you rebase or merge gh-pages into this branch?

Done. Thanks.

2023-06-21 03:59 UTC, wdconinc commented
I could review but was going to let @klieret comment.

2023-06-27 19:30 UTC, klieret requested changes

2023-06-27 19:30 UTC, klieret commented on README.md
> +# Title of the lesson
<-

2023-06-27 19:31 UTC, klieret commented
The thing is that this repository is currently not really used. It was meant to contain the intersection between the github and gitlab trainings, but we never really figured out a good way to combine both of these trainings (so this is now certainly already out of sync)...

2023-06-28 03:37 UTC, amanmdesai commented on README.md
> +# Title of the lesson
Thanks. Implemented.

2023-07-06 10:10 UTC, amanmdesai commented
> The thing is that this repository is currently not really used. It was meant to contain the intersection between the github and gitlab trainings, but we never really figured out a good way to combine both of these trainings (so this is now certainly already out of sync)...

I see, thanks. I did not notice that it was out of sync for that reason.

2023-07-24 16:49 UTC, closed without merging